### ISSUE TITLE
The `style` prop expects a mapping from style properties

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-pwa#112]
In a demo, all pages are loading properly but when we try to go to a post it doesn't load and we find the following error in the console: "The 'style' prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX."

This error can be reproduced going to: https://ssr.wp-pwa.com/?siteId=3RnPFS9GDGPMdNMFw&env=prod&static=https://static.wp-pwa.com and trying to load a post

In the console you will see:

![Screen Shot 2018-10-04 at 18.44.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9625a0f85c42001167f9b7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f76b7191a379e70c2f55415a47be5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb50f04ce04856a5143761f43b.png)

And if you enter in the react link provided (https://reactjs.org/docs/error-decoder.html/?invariant=62&args[]=) you can see:

![Screen Shot 2018-10-04 at 18.44.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b9625a0f85c42001167f9b7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f76b7191a379e70c2f55415f4dbe5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb50f04ce04852a1123367f43b.png)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_e2f6)

**Comment by DAreRodz** [comment]
I seems like a problem with the execution order of processors that we are using to transform HTML to React... I'll take a look tomorrow.

**Comment by luisherranz** [comment]
Thanks @darerodz!
