### ISSUE TITLE
Create bug priority system

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#115]
Each time someone creates an issue, some fields must be populated. They are the multipliers of a final result:
- Size:
  - **pageviews**: the sum of pageviews affected by this problem (x pageviews, in millions).
- Environment:
  - **production**: the problem appears in a production site (x10).
  - **starting integration**: the problem appears during the initial phases of the integration process (x3).
  - **finishing integration**: the problem appears during the last phases of the integration process (x6).
  - **demo**: the problem appears in a demo site (x1).
- Range:
  - **high**: the problem appears in most of the site pages (x5).
  - **medium**: the problem appears in half of the site pages (x3).
  - **low**: the problem only appears in a small percentage of the site pages (x1).
- Behaviour:
  - **critical**: the problem is totally blocking the usage of a site (x5).
  - **not-nice**: users can live with the problem, but it's something not nice to have (x1).
- Mass:
  - **everyone**: the problem affects most of the users (x5).
  - **marginal**: the problem only affects a small percentage of the users (x1).
- Miscellanea:
  - **referrer**: the site belongs to a customer/group considered to be a referrer (x3).
  - **case study**: the site is considered to be a potential case study (x5).

~Each Monday morning we will **multiply by 2** each remaining bug.~

*Multipliers can be adjusted at will when we learn how they work.*

**Comment by Poliuk** [comment]
I love it @luisherranz. In order to avoid small issues to remain unsolved, maybe we could add another rule that will increase the priority as the time passes. For example adding 3 points every 7 days or something like this.

**Comment by luisherranz** [comment]
We need another system for the custom features and internal tools like `ads-form`.

**Comment by luisherranz** [comment]
I think the first automation step would be to create a codesandbox with a form which ask you questions and gives you the final priority and text to copy and paste in the issue:

```
Size: **(2M)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[300]**
```

**Comment by luisherranz** [comment]
Done: https://cs.frontity.io/
