### ISSUE TITLE
[13.38] React hydration forces re render of the whole app

### ISSUE THREAD

**Issue by orballo** [wp-pwa/wp-pwa#132]
This only happens in production.

Link to sites where the error happens:

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A4

https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A21

---

Pageviews: **(0.535M)**
Environment: **demo (x1)**
Range: **high (x5)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[13.38]**

https://frontity.pipedrive.com/deal/53
https://frontity.pipedrive.com/deal/50

**Comment by SantosGuillamot** [comment]
#notify
