### ISSUE TITLE
[450] AMP urls should be the post link + /amp/

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-pwa#139]
Right now the url (location) of AMP sent to Analytics has this format:
`/best-google-amp-and-facebook-instant-articles-plugins-for-wordpress/?siteId=PHAzpvws5pvZw7XuW&env=prod&dev=false&singleType=post&singleId=1173&initialUrl=https://blog.frontity.com/best-google-amp-and-facebook-instant-articles-plugins-for-wordpress/`

It should be the post link + `/amp/`, like this:
`/best-google-amp-and-facebook-instant-articles-plugins-for-wordpress/amp/`

It should also respect the queries:
`/best-google-amp-and-facebook-instant-articles-plugins-for-wordpress/?campaign=something` => `/best-google-amp-and-facebook-instant-articles-plugins-for-wordpress/amp/?campaign=something`

----

https://frontity.pipedrive.com/deal/174

Pageviews: **(3)**
Environment: **production (x10)**
Range: **medium (x3)**
Behaviour: **not-nice (x1)**
Mass: **everyone (x5)**
PRIORITY: **[450]**

https://frontity.pipedrive.com/organization/36

**Comment by luisherranz** [comment]
Maybe it is related to #134
