### ISSUE TITLE
Create auto-demos tool for CS

### ISSUE THREAD

**Issue by DAreRodz** [wp-pwa/wp-pwa#151]
This tool should:

- [ ] check if the site is a WP blog with a public REST API
- [ ] add the site in DB with default settings
- [ ] generate an individual URL for the demo
- [ ] handle every possible error

The auto-demos tool will end up becoming a demo generator for customers.

More info [here](https://docs.google.com/document/d/1nlxXfKOqmgNQ1DTSnH50KnZjUz-0OffU7DbaD22uO9I/edit#)
Work in progress [here](https://codesandbox.io/s/n06y86o0k0)

**Comment by tanzaniatech** [comment]
Hi i dont know if its right place to write this but i really need this on our website, we send request hours ago can you please help. Please...

**Comment by luisherranz** [comment]
Hi @tanzaniatech. Thanks for stopping by!

@SantosGuillamot just told me we've sent you a demo to your email. Please check it out.

From now on, contact us using our support email: https://frontity.com/get-help. We can give you better support there :)
