### ISSUE TITLE
[24] Blockquotes should look like desktop version

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-pwa#153]
The actual style for blockquotes is not valid for the client and they want to show it like the desktop version.

Relevant url:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A37

----
https://frontity.pipedrive.com/deal/218
Site pageviews: **(0.67)**
Extra group sites: **(1)**
Extra group pageviews: **(0.23)**
Development size: **(1)**
Blocking: **expected (x3)**
Environment: **integration is finishing (x10)**
Reusability potential: **ad-hoc (x1)**
PRIORITY: **[24]**

**Comment by luisherranz** [comment]
Can be solved with Custom CSS

**Comment by SantosGuillamot** [comment]
It has been solved adding Custom CSS
