### ISSUE TITLE
[79] Valenti reviews should show like desktop

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-pwa#162]
Valenti theme has reviews like this:
https://valenti.cubellthemes.com/music/techno/audio-and-review-top-stars/

We need to support them. Relevant url:
https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A44

Maybe it is related to this issue:
https://github.com/frontity/saturn-theme/issues/199

Although the reviews are different, they seem to use the same theme.

----
https://frontity.pipedrive.com/deal/427
Site pageviews: **(0.01)**
Extra group sites: **(5)**
Extra group pageviews: **(0.6)**
Development size: **(13)**
Blocking: **no frontity without it (x15)**
Environment: **integration is finishing (x10)**
Reusability potential: **marginal (x2)**
Referrer: **yes (x3)**
PRIORITY: **[79]**

**Comment by DAreRodz** [comment]
Allow icons (empty `<i>` tags) by default.
