### ISSUE TITLE
[5895] After swipe Doubleclick ads are not showing

### ISSUE THREAD

**Issue by SantosGuillamot** [wp-pwa/wp-pwa#163]
It seems that the script is working because the ad is not empty

Relevant url: https://docs.google.com/spreadsheets/d/1FWcvX7KiLAppGW2qOICxs8ATWqV1uEsCVdTnq5mK7q8/edit#gid=0&range=A48

----
#cs: @SantosGuillamot 
#supporter: @luisherranz 

https://frontity.pipedrive.com/deal/427
Pageviews: **(0.01)**
Environment: **integration is finishing (x6)**
Range: **high (x5)**
Behaviour: **no frontity without it (x10)**
Mass: **everyone (x5)**
Referrer: **yes (x3)**
PRIORITY: **[45]**

https://frontity.pipedrive.com/deal/153
Pageviews: **(0.78)**
Environment: **integration is finishing (x6)**
Range: **high (x5)**
Behaviour: **no frontity without it (x10)**
Mass: **everyone (x5)**
Case Study: **yes (x5)**
PRIORITY: **[5850]**

**Comment by SantosGuillamot** [comment]
In deal 153, on first load of a category it shows all the ads. After swiping between categories, the first ad doesn't show but the rest of them usually do.

**Comment by luisherranz** [comment]
It only fails in CSR, when ads are rendered after SSR in a new pageview. It looks like calls to the adserver are fine because the iframes are there, but the ads are empty.
