### ISSUE TITLE
[Design] Figure out how to work with local and remote frontity-npm packages

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#173]
What we need:
- [x] A developer using Frontity should be able to commit their package to git and never publish it. It must work when cloning the project and running it in another machine without having to publish anything to npm. If symlinks are used, they must work when cloning them in another machine or even system (from Windows in development to Ubuntu in production for example).
- [x] A Frontity package created in the folder `/package/my-extension` must be ready to be published in npm using `npm publish`.
- [x] Developers shouldn't have to use commands to configure this packages, if any configuration or linking has to be done, it needs to be done by frontity in `frontity start`.
- [x] A Frontity package must not have a prepublish build phase with any type of transpilation. It is a `src` folder with the esModule code. All transpilation should be done when using `frontity start`.
- [ ] Frontity can know at start (`frontity start`) which packages are installed by checking the settings files or by checking the keywords. We should avoid the need to write down the list of plugins used in some file.
- [x] If something like symlinking is used, it must work flawlessly in macOS, Linux and Windows.
- [x] The command `npm install` must install the dependencies of ALL PACKAGES in the root. Dependencies of packages in `/package/my-extension` must be treated as if they were npm modules found in `node_modules`. 

Tools to consider:
- `npm install /package/my-package`: https://docs.npmjs.com/cli/install
- `yalc`: https://github.com/whitecolor/yalc
- ...

**Comment by luisherranz** [comment]
Investigate what are [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) and if they can be useful.

**Comment by DAreRodz** [comment]
I created a [simple project](https://github.com/darerodz/example-project) for testing folders as dependencies. It works perfectly in macOS, Ubuntu and Windows 10, and it covers most of the points above.

The project has an npm package inside `/packages/example-package` folder as a dependency. That package has also an external dependency, and both packages are installed in `/node_modules` after executing `npm install` from the root folder.

What it is not clear to me right now is how **settings** and **packages** relate each other, and what kind of *configuration* `frontity start` should do. For example, it that command which adds the content of `/packages` folder as dependencies?

**Comment by luisherranz** [comment]
Awesome. This is perfect for our use case. Thanks!
