### ISSUE TITLE
Configure clicky in GTM for MyR

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#20]
https://clicky.com/help/custom/manual

**Comment by luisherranz** [comment]
Clicky code is: 247679

**Comment by luisherranz** [comment]
UA-71902-5

**Comment by orballo** [comment]
Done again :smile:

**Comment by luisherranz** [comment]
Reopened as we can solve the problem with intermediate pageviews:
https://clicky.com/help/custom#pageview_disable

First, disable pageviews using:
```js
var clicky_custom = clicky_custom || {};
  clicky_custom.pageview_disable = 1;
```
And then  use `clicky.pageview()` on each virtualPageView. It doesn't need parameters:
```
If you use clicky.pageview(), don't pass it any parameters. It will automatically grab the current URL and the page title and send them our way.
```

**Comment by luisherranz** [comment]
Not implemented finally because the global 'clicky' variable is not defined when the first virtualPageview is sent.
