### ISSUE TITLE
GTM anonymizer not working sometimes

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#25]
Steps to reproduce the bug:
 - Go to https://herencia.net/?force=true. Anynomizer works:
![screen shot 2018-01-26 at 16 32 01](https://user-images.githubusercontent.com/3305402/35447011-c907b8ba-02b6-11e8-93e6-69cf4185d488.png)

- Swipe to the right (https://herencia.net/categoria/asociaciones/). It doesn't work:
![screen shot 2018-01-26 at 16 34 03](https://user-images.githubusercontent.com/3305402/35447021-ce7d16fa-02b6-11e8-92d5-c47c66336bf5.png)

**Comment by DAreRodz** [comment]
Problem solved naming our Google Analytics instance with ```wpPwa``` in the GTM snippets.
