### ISSUE TITLE
Check rollbar's script error

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#36]
https://rollbar.com/worona/pwa/items/47/?person_page=0&#graphs

It looks like it happens only on Chrome 43 and older so we should install it and check the error origin.

**Comment by luisherranz** [comment]
![Screen Shot 2018-01-31 at 12.00.32.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58af0e4ea157412000799534/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226457f26b7191a379ed0c2b51415c4cbe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ff542e74951a6133464f43b.png)

**Comment by luisherranz** [comment]
http://google-chrome.en.uptodown.com/mac/download/263261

**Comment by luisherranz** [comment]
```
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined(anonymous function) @ saturn-app-theme-worona-src-pwa-index.f9132a9ac10d21a634ec.js:1
```

**Comment by DAreRodz** [comment]
open -a ~/Desktop/Google\ Chrome.app --args --profile-directory=prof

**Comment by DAreRodz** [comment]
Closed at https://github.com/wp-pwa/saturn-theme/commit/b70b657d52f1c558b7bdf404cf455eac0bba5d9c.
