### ISSUE TITLE
Add pwa and amp to our Analytics

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#56]
For anonymous urls, something like this:
/anonymous/pwa/a729f0777e591
/anonymous/amp/a729f0777e591

For the page titles, something like this:
anonymous - amp - single - post - a729f0777e591
anonymous - pwa - single - post - a729f0777e591
https://viviendosanos.com/ - amp - single - post - 6260
https://viviendosanos.com/ - pwa - single - post - 6260

**Comment by DAreRodz** [comment]
Closed at 07fb059af1205d973330d2541ed2429ba9999888
