### ISSUE TITLE
Measure and minimize ads destruction time

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#70]
We should use average timings. If an ad takes 100ms to be destroyed and we have 4 ads per page on average, ads destruction should take 400ms, not more.

Child of https://github.com/frontity/frontity/issues/68

**Comment by DAreRodz** [comment]
The time an ad needs to be destroyed is not significant. On production, with a CPU x6 slowdown, it takes an average of ~ 15ms, plus other 15ms of recalculate style and layout. At this moment, I think it is better to leave this at it is, with the ads being removed asynchronously and avoiding a frame rate slowdown.
