### ISSUE TITLE
Analyze lazyload libraries

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#72]
For example https://github.com/verlok/lazyload/issues/187

Implementation of verlok's library: https://codesandbox.io/s/20306yk96p
Implementation with our Slider:
- `vanilla-lazuload 8.x`: https://codesandbox.io/s/82n89qw1v9
- `vanilla-lazyload 10.x`: https://codesandbox.io/s/3y9vv9r9wm
- `vanilla-lazyload 10.x + polyfill`: https://codesandbox.io/s/1vj9yp9np3

An important feature is horizontal support.

Child of https://github.com/frontity/frontity/issues/71

---

Lazy loading docs from Google: https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/
MDN IntersectionObserver:
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API
IntersectionObserver polyfill: https://github.com/w3c/IntersectionObserver/tree/master/polyfill

**Comment by orballo** [comment]
I was reading that verlok's library has implemented a converter to `webp` images (example: https://www.andreaverlicchi.eu/lazyload/demos/to_webp_some.html), maybe we could try this as well? I don't know if it's possible to convert them with our media CDN.

Currently `webp` is only supported by Chrome, and here is the percentage of frontity users that use it:
![Screen Shot 2018-08-29 at 11.49.16.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6202d4f976d5001232e9d2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fa6b7191a379ee0c2f58415e48be5d4a1f06a3a3dc78e2a436628f0e0feed2695875c23d42afbd811fbf03bc72d84bd4e3e89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5df348e74854a2103264f43b.png)

We could however,  if all this is worth the implementation, use the same solution for `JPEG2000` images, supported by Safari (the green one in the char above).
