### ISSUE TITLE
Refactor with new design and memoize

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa#76]
Requires https://github.com/frontity/frontity/issues/75

Child of https://github.com/frontity/frontity/issues/74

We should try to maximize the use of `memoize`.

**Comment by DAreRodz** [comment]
The repo is https://github.com/frontity/h2r

**Comment by DAreRodz** [comment]
This processors must be moved to [h2r](https://github.com/frontity/h2r) repo:

**From low-priority processors**
- [x] audio
- [x] facebok
- [x] iframe
- [x] instagram
- [x] removeDoctypeHeadTags
- [x] removeHtmlBodyTags
- [x] removeHidden
- [x] removeScript
- [x] removeTagStyle
- [x] removeWpEmbeddedContent
- [x] soundcloud
- [x] twitter
- [x] video
- [x] youtube

**From medium-priority processors**
- [x] removeAmpColWidth
- [x] removeAmpIds
- [x] removeAmpListTypes
- [x] removeInlineStyles
